
(setq elfeed-feeds
      '(
        ;; Programming
        ("http://lambda-the-ultimate.org/rss.xml" programming cs)
        ("http://blog.thimbleweedpark.com/rss" games programming adventures)
        ("http://technomancy.us/feed/atom.xml" programming)
        ("http://wadler.blogspot.it/atom.xml" cs fp programming)
        ("http://conscientiousprogrammer.com/atom.xml" programming)
        ("http://tratt.net/laurie/blog/entries.rss" programming)
        ("http://nakkaya.com/rss-feed" programming)
        ("http://feeds.feedburner.com/ArcaneSentiment" programming)
        ("http://matt.might.net/articles/feed.rss" programming cs)
        ("http://programmingisterrible.com/rss" programming)
        ("http://aegisknight.org/feed" programming)
        ("http://www.lunaryorn.com/feed.atom" programming)
        ("https://rkrishnan.org/atom.xml" programming)
        ("http://chromakode.com/recent.atom" programming)
        ("http://www.newartisans.com/rss.xml" programming)
        ("http://aliquote.org/memos/rss/" programming)
        ("http://blog.racket-lang.org/feeds/posts/default" programming racket)
        ("http://belkadan.com/blog/atom" programming)
        ("http://blog.fogus.me/feed/" programming)
        ("https://www.thanassis.space/rss.xml" programming)
        ("http://steve-yegge.blogspot.com/atom.xml" programming)
        ("http://journal.stuffwithstuff.com/atom.xml" programming)
        ("https://gbracha.blogspot.com/feeds/posts/default" programming)
        ("https://chriskiehl.com/rss.xml" programming)
        ("https://queue.acm.org/rss/feeds/latestitems.xml" cs)
        ("https://blog.veitheller.de/feed.rss" programming)
        ("https://www.hillelwayne.com/index.xml" programming)

        ;; Programming – Perl
        ("http://pl6anet.org/atom.xml" perl programming)
        ("https://rjbs.manxome.org/rubric/entries/user/rjbs/has_body/1?format=rss")

        ;; Programming – Haskell
        ("http://www.haskell-ita.it/atom.xml" haskell fp programming)
        ("http://planet.haskell.org/rss20.xml" haskell fp programming)
        ("http://donsbot.wordpress.com/feed/" haskell fp programming)
        ("http://jaspervdj.be/rss.xml" programming haskell)
        ("http://bitemyapp.com/" programming haskell)
        ("http://lambda.jstolarek.com/feed/" programming haskell)
        ("http://sigfpe.blogspot.com/feeds/posts/default" cs programming haskell)
        ("http://matthiasnehlsen.com/atom.xml" fp programming)
        ("http://chrisdone.com/rss.xml" haskell fp programming)
        ("https://byorgey.wordpress.com/feed/" haskell fp programming math)
        ("http://joeyh.name/blog/index.rss" haskell fp programming)
        ("https://pbrisbin.com/feed/index.xml" haskell fp programming)
        ("http://comonad.com/reader/feed/" haskell programming cs)
        ("https://chrispenner.ca/atom.xml" haskell programming fp)

        ;; Programming – Lisp
        ("http://planet.lisp.org/rss20.xml" lisp fp programming)
        ("https://lisp.space/feed.xml" lisp fp programming)
        ("http://lispy.wordpress.com/feed/" lisp fp programming)
        ("http://xach.livejournal.com/data/atom" lisp fp programming)
        ("http://funcall.blogspot.com/feeds/posts/default" lisp fp programming)
        ("http://feeds2.feedburner.com/stevelosh" lisp fp programming)
        ("http://planet.emacs-es.org/rss20.xml" lisp fp programming es)
        ("http://www.scheme.dk/planet/atom.xml" scheme)
        ("https://lisp.sh/feed.atom" racket)
        ("https://recursive.games/rss.xml" lisp programming games)
        ("http://www.lispology.com/rss?JHE+3" lisp programming)

        ;; Programming – Clojure
        ("http://planet.clojure.in/atom.xml" clojure programming)
        ("http://gigasquidsoftware.com/atom.xml" clojure programming)

        ;; Math
        ("http://blogs.ams.org/visualinsight/feed/" math)
        ("http://blogs.ams.org/blogonmathblogs/" math)
        ("http://jeremykun.wordpress.com/feed/" math programming cs)
        ("https://jeltsch.wordpress.com/feed/" math cs programming)
        ("http://mathlesstraveled.com" math)
        ("http://blog.stephenwolfram.com/feed/" math science)
        ("http://blog.ifem.co.uk/feed/" math)
        ("https://egtheory.wordpress.com/feed/" cs evolution gametheory)
        ("http://math.andrej.com/feed/" cs math)
        ("http://blog.acolyer.org/feed/" cs)
        ("http://www.scottaaronson.com/blog/?feed=rss2" cs)
        ("https://golem.ph.utexas.edu/category/atom11.xml" math)
        ("https://mathbabe.org/feed/" math)
        ("https://terrytao.wordpress.com/feed/" math)

        ;; Data
        ("https://modern-sql.com/feed" data sql)
        ("https://kieranhealy.org/index.xml" data visualization R)
        ("https://chris-said.io/" data)
        ("http://datagenetics.com/feed/rss.xml" data)
        ("http://www.cs.cmu.edu/~pavlo//blog/feed.xml" data)
        ("https://caitlinhudon.com/feed/" data)
        ("https://www.locallyoptimistic.com/index.xml" data)
        ("https://meltano.com/blog/feed/" data etl)
        ("https://planet.postgresql.org/rss20.xml" data postgresql)

        ;; R
        ("https://4dpiecharts.com/feed/" R)

        ;; Emacs
        ("http://planet.emacsen.org/atom.xml" emacs)
        ("https://asylum.madhouse-project.org/blog/atom.xml" emacs programming)
        ("http://www.masteringemacs.org/feed/" emacs)
        ("https://emacs.wordpress.com/feed/" emacs)
        ("http://pragmaticemacs.com/" emacs)
        ("http://www.howardism.org/index.xml" emacs)

        ;; Vim
        ("http://howivim.com/feed.xml" vim)

        ;; Cinema
        ("http://www.i400calci.com/feed/" cinema interesting)

        ;; Music
        ("https://slippedisc.com/feed/" music classical)

        ;; Comics
        ("http://www.fumettologica.it/feed/" comics)
        ("http://xkcd.com/atom.xml" comics dailycomic)
        ("http://blog.xkcd.com/feed/" comics books)
        ("http://www.smbc-comics.com/rss.php" comics)
        ("http://feeds.feedburner.com/wondermark" comics)
        ("http://www.phdcomics.com/gradfeed.php" comics)
        ("http://abstrusegoose.com/atomfeed.xml" comics)
        ("http://www.casualvillain.com/Unsounded/feed/" comics)
        ("http://feeds.feedburner.com/zenpencils" comics)

        ;; SF
        ("http://scifiinterfaces.wordpress.com/feed/" sf ux ui)
        ("http://www.antipope.org/charlie/blog-static/atom.xml" sf )
        ("http://scifistorm.org/scifistorm.rdf" sf)
        ("http://lennesimoblogdellafantascienza.wordpress.com/feed/" sf)
        ("http://www.tor.com/feed" sf clutter)
        ("http://whatever.scalzi.com/feed/" sf)
        ("http://www.sfsignal.com/index.rdf" sf)
        ("http://auxiliarymemory.com/feed/" sf)
        ("http://andromedasf.altervista.org/feed/" sf)

        ;; Chess
        ("http://www.danamackenzie.com/blog/?feed=rss2" chess)

        ;; Personal blogs
        ("http://www.rousette.org.uk/blog/index.xml")
        ("http://cartesianfaith.com/feed/")
        ("http://jasmcole.com/feed/")
        ("http://susan-stepney.blogspot.com/feeds/posts/default?alt=rss" books science)
        ("http://www.joachim-breitner.de/blog_feed.rss")
        ("http://stephenramsay.us/atom.xml")
        ("https://alexschroeder.ch/wiki/feed/full/")
        ("https://mcristi.wordpress.com/feed/")
        ("http://www.charlespetzold.com/rss.xml")
        ("https://cartesianproduct.wordpress.com/feed/")
        ("http://regex.info/blog/feed" maybe)
        ("http://ariis.it/static/stream/rss.xml")
        ("http://babbagefiles.blogspot.com/feeds/posts/default" maybe)
        ("https://babbagefiles.xyz/index.xml" maybe)
        ("http://bactra.org/notebooks/index.rss")
        ("http://bactra.org/weblog/index.rss")
        ("http://emacsninja.com/feed.atom")
        ("http://r6.ca/blog/feed.atom" maybe)
        ("https://fare.livejournal.com/data/atom" maybe)
        ("https://shitpost.plover.com/index.atom")
        ("https://grumpygamer.com/rss")
        ("https://two-wrongs.com/feed.xml")
        ("https://11011110.github.io/blog/feed.xml")
        ("https://drewdevault.com/feed.xml" cs)
        ("https://falsemachine.blogspot.com/feeds/posts/default?alt=rss" books)
        ("https://ww.telent.net/news.rss")
        ("http://johnj.com/feed.xml")
        ("https://blog.nelhage.com/atom.xml")
        ("http://pchiusano.github.io/feed.xml")
        ("https://beepb00p.xyz/atom.xml")
        ("https://willschenk.com/feed.xml" maybe)
        ("https://sandymaguire.me/atom.xml")
        ("https://reasonablypolymorphic.com/atom.xml")
        ("http://muratbuffalo.blogspot.com/feeds/posts/default" cs distributed-systems)
        ("https://www.singlelunch.com/feed/" maybe)
        ("https://fluca1978.github.io/feed.xml")

        ;; misc stuff
        ("http://boingboing.net/index.xml" clutter)
        ("http://nautil.us/rss/all")
        ("http://usesthis.com/feed/" setup)
        ("http://chneukirchen.org/trivium/index.atom" links interesting)
        ("http://www.bytecellar.com/feed/" retrocomputing)
        ("http://basalgangster.macgui.com/RetroMacComputing/The_Long_View/rss.xml")
        ("http://ilovetypography.com/feed")
        ("http://www.ericrochester.com/atom.xml")
        ("http://blog.datadive.net/feed/")
        ("https://rpgcharacters.wordpress.com/feed/" rpg maps)
        ("https://lovecraftianscience.wordpress.com/feed/")
        ("https://damiengwalter.com/feed/")
        ("http://themacro.com/feed.xml")
        ("http://www.datatau.com/rss")
        ("https://jasmcole.com/feed/")
        ("http://www.netflixlovers.it/rss" netflix clutter)
        ("http://lanyrd.com/places/bologna/feed/" conferences bologna)
        ("http://onethingwell.org/rss" software)
        ("https://functionaljobs.com/jobs/search/?q=berlin&format=rss" jobs fp)
        ("https://twobithistory.org/feed.xml")
        ("http://catless.ncl.ac.uk/risksrss2.xml")
        ("http://tech.marksblogg.com/feeds/all.atom.xml")
        ("http://www.elidedbranches.com/feeds/posts/default")
        ("https://lethain.com/feeds/" maybe engineering management)
        ("http://n-gate.com/index.rss" interesting)
        ("https://thetechnicalgeekery.com/feed.xml" maybe)
        ("https://controlaltbackspace.org/feed.xml" maybe)
        ("https://apod.nasa.gov/apod.rss")
        ("https://www.gatesnotes.com/rss" books)
        ("https://plaintextproject.online/feed.xml")

        ;; maybe
        ("https://blog.tymoon.eu/" maybe)
        ("http://adereth.github.io/atom.xml" maybe)
        ("https://eight2late.wordpress.com/feed/" maybe)
        ("http://feeds.akkartik.name/kartiks-scrapbook" maybe)
        ("https://backchannel.com/feed" maybe)
        ("http://realworldclojure.com/feed.xml" maybe)
        ("http://www.shortscience.org/rss.xml" maybe)
        ("https://interi.org/feed/" maybe)
        ("http://www.camilletalk.com/whilefalse?format=RSS" maybe)
        ("http://vicsydev.blogspot.com/feeds/posts/default?alt=rss" maybe)
        (" http://www.the2bears.com/?p=614" maybe gaming)
        ("http://dannyreviews.com/rss.xml" maybe books)
        ("http://bravenewgeek.com/feed/" maybe)
        ("http://www.nonsolo8bit.it/feed/" maybe 8bit programming)
        ("https://www.dgmlive.com/feeds/rss/diaries" maybe)
        ("http://acta-lingweenie.blogspot.com/feeds/posts/default" maybe)
        ("https://p1k3.com/feed" maybe)
        ("http://www.felienne.com/feed" maybe)
        ("https://www.filfre.net/feed/" maybe)
        ("http://export.arxiv.org/rss/cs" cs maybe)
        ("http://linesandcolors.com/feed/" art maybe)
        ("http://www.cachestocaches.com/feed/" maybe)
        ("https://adventuregamers.com/rss/" maybe games adventures)
        ("https://acoup.blog/feed/" maybe)
        ("https://kiwihellenist.blogspot.com/feeds/posts/default" maybe)

        ;; suggested by Dan Luu -- 2016/05/03
        ("http://blog.nullspace.io/feed.xml" danluu maybe)
        ("http://akaptur.com/atom.xml" danluu maybe)
        ("http://www.chrisfenton.com/feed/" danluu maybe)
        ("https://codewords.recurse.com/feed.xml" danluu maybe)
        ("http://mcfunley.com/feed/atom" danluu maybe)
        ("http://davidad.github.io/atom.xml" danluu maybe)
        ("http://eli.thegreenplace.net/feeds/all.atom.xml" danluu maybe)
        ("http://www.evanjones.ca/index.rss" danluu maybe)
        ("https://blog.lse.epita.fr/rssfeed.xml" danluu maybe)
        ("http://neverworkintheory.org/feed.xml" danluu maybe)
        ("http://feeds.feedburner.com/GustavoDuarte" danluu maybe)
        ("https://www.blogger.com/feeds/4534865332750558938/posts/default" danluu maybe)
        ;; ("http://blog.regehr.org/comments/feed" danluu maybe)
        ("https://www.snellman.net/blog/rss-index.xml" danluu maybe)

        ;; Biking
        ("http://ridinggravel.com/feed/" bikes)
        ("https://www.cyclingabout.com/feed/" bikes)))
